return {
  ["spriter_data"] = {
    ["scml_version"] = 1.0, 
    ["generator"] = "BrashMonkey Spriter", 
    ["generator_version"] = "a4.1", 
    ["folder"] = {
      ["id"] = 0, 
      ["file"] = {
        ["width"] = 220, 
        ["height"] = 150, 
        ["id"] = 0, 
        ["name"] = "rightleg.png", 
      },
      ["file"] = {
        ["width"] = 100, 
        ["height"] = 200, 
        ["id"] = 1, 
        ["name"] = "rightarm.png", 
      },
      ["file"] = {
        ["width"] = 200, 
        ["height"] = 200, 
        ["id"] = 2, 
        ["name"] = "leftleg.png", 
      },
      ["file"] = {
        ["width"] = 250, 
        ["height"] = 250, 
        ["id"] = 3, 
        ["name"] = "torso.png", 
      },
      ["file"] = {
        ["width"] = 200, 
        ["height"] = 200, 
        ["id"] = 4, 
        ["name"] = "head.png", 
      },
      ["file"] = {
        ["width"] = 150, 
        ["height"] = 300, 
        ["id"] = 5, 
        ["name"] = "leftarm.png", 
      },
      ["file"] = {
        ["width"] = 200, 
        ["height"] = 200, 
        ["id"] = 6, 
        ["name"] = "head2.png", 
      },
    },
    ["entity"] = {
      ["id"] = 0, 
      ["name"] = "", 
      ["animation"] = {
        ["length"] = 1000, 
        ["id"] = 0, 
        ["name"] = "run", 
        ["mainline"] = {
          ["key"] = {
            ["id"] = 0, 
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 0, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 240, 
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 1, 
            },
          },
          ["key"] = {
            ["id"] = 2, 
            ["time"] = 480, 
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 2, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 2, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 2, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 2, 
            },
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 2, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 2, 
            },
          },
          ["key"] = {
            ["id"] = 3, 
            ["time"] = 700, 
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 3, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 3, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 3, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 3, 
            },
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 3, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 3, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 0, 
          ["key"] = {
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 354.685454, 
              ["file"] = 4, 
              ["y"] = 111, 
              ["x"] = -34, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.455, 
              ["pivot_y"] = 0.455, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 359.151236, 
              ["file"] = 4, 
              ["y"] = 104, 
              ["x"] = -46, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.455, 
              ["pivot_y"] = 0.455, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["angle"] = 5.964487, 
              ["file"] = 4, 
              ["y"] = 113, 
              ["x"] = -46, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.455, 
              ["pivot_y"] = 0.455, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["angle"] = 0.881404, 
              ["file"] = 4, 
              ["y"] = 105, 
              ["x"] = -46, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.455, 
              ["pivot_y"] = 0.455, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 1, 
          ["key"] = {
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 352.874984, 
              ["file"] = 3, 
              ["y"] = -26, 
              ["x"] = -29, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.46, 
              ["pivot_y"] = 0.524, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 355.467738, 
              ["file"] = 3, 
              ["y"] = -35, 
              ["x"] = -29, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.46, 
              ["pivot_y"] = 0.524, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["angle"] = 359.639654, 
              ["file"] = 3, 
              ["y"] = -26, 
              ["x"] = -29, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.46, 
              ["pivot_y"] = 0.524, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["angle"] = 358.2212, 
              ["file"] = 3, 
              ["y"] = -34, 
              ["x"] = -29, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.46, 
              ["pivot_y"] = 0.524, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 2, 
          ["key"] = {
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 12.994617, 
              ["file"] = 1, 
              ["y"] = 17, 
              ["x"] = -79, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.76, 
              ["pivot_y"] = 0.31, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 15.780753, 
              ["file"] = 1, 
              ["y"] = 8, 
              ["x"] = -79, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.76, 
              ["pivot_y"] = 0.31, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["angle"] = 4.085617, 
              ["file"] = 1, 
              ["y"] = 17, 
              ["x"] = -79, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.76, 
              ["pivot_y"] = 0.31, 
            },
          },
          ["key"] = {
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["file"] = 1, 
              ["y"] = 9, 
              ["x"] = -79, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.76, 
              ["pivot_y"] = 0.31, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 3, 
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 314.274776, 
              ["file"] = 5, 
              ["y"] = 46, 
              ["x"] = 27, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.446667, 
              ["pivot_y"] = 0.886667, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 306.326826, 
              ["file"] = 5, 
              ["y"] = 40, 
              ["x"] = 24, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.446667, 
              ["pivot_y"] = 0.886667, 
            },
          },
          ["key"] = {
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["angle"] = 27.699473, 
              ["file"] = 5, 
              ["y"] = 48, 
              ["x"] = 34, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.446667, 
              ["pivot_y"] = 0.886667, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["angle"] = 46.218875, 
              ["file"] = 5, 
              ["y"] = 40, 
              ["x"] = 34, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.446667, 
              ["pivot_y"] = 0.886667, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 4, 
          ["key"] = {
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 241.854135, 
              ["file"] = 2, 
              ["y"] = -113, 
              ["x"] = -42, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.215, 
              ["pivot_y"] = 0.775, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 254.008472, 
              ["file"] = 2, 
              ["y"] = -122, 
              ["x"] = -42, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.215, 
              ["pivot_y"] = 0.775, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["angle"] = 18.541645, 
              ["file"] = 2, 
              ["y"] = -108, 
              ["x"] = 9, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.215, 
              ["pivot_y"] = 0.775, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["angle"] = 8.746162, 
              ["file"] = 2, 
              ["y"] = -116, 
              ["x"] = 9, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.215, 
              ["pivot_y"] = 0.775, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 5, 
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 135.954841, 
              ["file"] = 0, 
              ["y"] = -110, 
              ["x"] = -16, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.837966, 
              ["pivot_y"] = 0.748856, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 1, 
            ["time"] = 240, 
            ["object"] = {
              ["angle"] = 115.641006, 
              ["file"] = 0, 
              ["y"] = -115, 
              ["x"] = -14, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.837966, 
              ["pivot_y"] = 0.748856, 
            },
          },
          ["key"] = {
            ["id"] = 2, 
            ["time"] = 480, 
            ["object"] = {
              ["file"] = 0, 
              ["y"] = -108, 
              ["x"] = -41, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.837966, 
              ["pivot_y"] = 0.748856, 
            },
          },
          ["key"] = {
            ["id"] = 3, 
            ["time"] = 700, 
            ["object"] = {
              ["angle"] = 16.798372, 
              ["file"] = 0, 
              ["y"] = -116, 
              ["x"] = -41, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.837966, 
              ["pivot_y"] = 0.748856, 
            },
          },
        },
      },
      ["animation"] = {
        ["length"] = 1000, 
        ["id"] = 1, 
        ["name"] = "idle", 
        ["mainline"] = {
          ["key"] = {
            ["id"] = 0, 
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 0, 
            },
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 0, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 500, 
            ["object_ref"] = {
              ["timeline"] = 0, 
              ["z_index"] = 0, 
              ["id"] = 0, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 1, 
              ["z_index"] = 1, 
              ["id"] = 1, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 2, 
              ["z_index"] = 2, 
              ["id"] = 2, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 3, 
              ["z_index"] = 3, 
              ["id"] = 3, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 4, 
              ["z_index"] = 4, 
              ["id"] = 4, 
              ["key"] = 1, 
            },
            ["object_ref"] = {
              ["timeline"] = 5, 
              ["z_index"] = 5, 
              ["id"] = 5, 
              ["key"] = 1, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 0, 
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 49.424784, 
              ["file"] = 0, 
              ["y"] = -114, 
              ["x"] = -42, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.761651, 
              ["pivot_y"] = 0.771715, 
            },
          },
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["angle"] = 49.424784, 
              ["file"] = 0, 
              ["y"] = -110, 
              ["x"] = -46, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.763635, 
              ["pivot_y"] = 0.809314, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 1, 
          ["key"] = {
            ["id"] = 0, 
            ["object"] = {
              ["file"] = 1, 
              ["y"] = 23, 
              ["x"] = -76, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.83, 
              ["pivot_y"] = 0.365, 
            },
          },
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["angle"] = 1.432096, 
              ["file"] = 1, 
              ["y"] = 28, 
              ["x"] = -74, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.84, 
              ["pivot_y"] = 0.365, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 2, 
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 302.860953, 
              ["file"] = 2, 
              ["y"] = -113, 
              ["x"] = 9, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.213571, 
              ["pivot_y"] = 0.71323, 
            },
          },
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["angle"] = 302.860953, 
              ["file"] = 2, 
              ["y"] = -109, 
              ["x"] = 13, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.207624, 
              ["pivot_y"] = 0.740881, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 3, 
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 0, 
            ["object"] = {
              ["y"] = 92, 
              ["x"] = -141, 
              ["folder"] = 0, 
              ["file"] = 3, 
            },
          },
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["y"] = 94, 
              ["x"] = -142, 
              ["folder"] = 0, 
              ["file"] = 3, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 4, 
          ["key"] = {
            ["spin"] = -1, 
            ["id"] = 0, 
            ["object"] = {
              ["angle"] = 2.397029, 
              ["file"] = 6, 
              ["y"] = 115, 
              ["x"] = -44, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.458041, 
              ["pivot_y"] = 0.465375, 
            },
          },
          ["key"] = {
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["angle"] = 359.565949, 
              ["file"] = 6, 
              ["y"] = 122, 
              ["x"] = -42, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.47, 
              ["pivot_y"] = 0.48, 
            },
          },
        },
        ["timeline"] = {
          ["id"] = 5, 
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 0, 
            ["object"] = {
              ["file"] = 5, 
              ["y"] = 44, 
              ["x"] = 36, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.433333, 
              ["pivot_y"] = 0.893333, 
            },
          },
          ["key"] = {
            ["spin"] = 0, 
            ["id"] = 1, 
            ["time"] = 500, 
            ["object"] = {
              ["file"] = 5, 
              ["y"] = 48, 
              ["x"] = 37, 
              ["folder"] = 0, 
              ["pivot_x"] = 0.44, 
              ["pivot_y"] = 0.893333, 
            },
          },
        },
      },
    },
  },
}
